baseURL = 'https://blog.shiva-tk.xyz/'
languageCode = 'en-us'
title = "Shiva's Blog"
theme = "smol"

# Parameters
[params]
    subtitle = "ฅ^•ﻌ•^ฅ"
    dateFmt = "02/01/2006 15:04"

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "posts"
        url = "/posts/"
        weight = 1

  [[menu.main]]
        identifier = "categories"
        name = "categories"
        url = "/categories/"
        weight = 2

  [[menu.main]]
        identifier = "tags"
        name = "tags"
        url = "/tags/"
        weight = 3

  [[menu.main]]
        identifier = "about"
        name = "about"
        url = "https://shiva-tk.xyz"
        weight = 4

[markup.goldmark.renderer]
  unsafe = true
